### ISSUE TITLE
ダウンロードができない

### ISSUE THREAD

**Issue by minahoku** [eggplants/getjump#20]
ジャンプやマガジン(comicdays)の購読分をログインした上でダウンロードしようとすると'NoneType' object is not subscriptableとエラーが

URL:
https://shonenjumpplus.com/magazine/3270296674401895776.json
https://comic-days.com/magazine/3269754496500226218.json

```
jget -u "xxxxxxxxxxx@xxxxxxxx" -p "xxxxxxxxxxxxxxxx" "https://shonenjumpplus.com/magazine/3270296674401895776.json"
```
```
get: https://shonenjumpplus.com/magazine/3270296674401895776.json
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\jget.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\getjump\main.py", line 175, in main
    get_one(args)
  File "c:\programdata\anaconda3\lib\site-packages\getjump\main.py", line 154, in get_one
    _, prev_title, ok = g.get(
  File "c:\programdata\anaconda3\lib\site-packages\getjump\getjump.py", line 76, in get
    series_title = j["series"]["title"].replace("/", "／")
TypeError: 'NoneType' object is not subscriptable
```
対応またはアドバイス等頂けますと嬉しいです

**Comment by eggplants** [comment]
課金が必要な関係上、`magazine`のテストができていなかったので報告助かります。

`magazine`の場合には`series`が`null`となるので、`j["series"]["title"]`でバグっています。

すぐ対応します。

**Comment by eggplants** [comment]
応答から雑誌名が取得できないのが厄介ですね…

**Comment by eggplants** [comment]
対応しました。

```bash
pip install -U getjump==1.3.0
getjump -o -u "xxxxxxxxxxx@xxxxxxxx" -p "xxxxxxxxxxxxxxxx" "https://shonenjumpplus.com/magazine/3270296674401895776.json"
```
