### ISSUE TITLE
ファイルが無い状態になるものがある

### ISSUE THREAD

**Issue by minahoku** [eggplants/getjump#21]
1. ダウンロードをしようとするとdoneと出るもののフォルダーだけ作られて中にファイルが無い状態になる
https://comic-days.com/magazine/3269754496500226218.json

```shellsession
$ jget -u "xxxxxxxxxxx@xxxxxxxx" -p "xxxxxxxxxxxxxxxx" "https://comic-days.com/magazine/3269754496500226218.json"
get: https://comic-days.com/magazine/3269754496500226218.json
saved: .\週刊少年マガジン\週刊少年マガジン２０２２年２９号
done.
```

---

2. ダウンロード自体はできファイルもあるが、作られたフォルダーの中に入らず親フォルダー内にファイル名が文字化けした状態で出力される
https://shonenjumpplus.com/episode/13933686331692600972.json

```shellsession
$ jget https://shonenjumpplus.com/episode/13933686331692600972.json
get: https://shonenjumpplus.com/episode/13933686331692600972.json
saved: .\久保さんは僕を許さない\[episode.001]久保さんは僕を許さない
done.
```

```text
荵・ｿ昴＆繧薙・蜒輔ｒ險ｱ縺輔↑縺Ы[episode.001]荵・ｿ昴＆繧薙・蜒輔ｒ險ｱ縺輔↑縺Ы00.jpg
荵・ｿ昴＆繧薙・蜒輔ｒ險ｱ縺輔↑縺Ы[episode.001]荵・ｿ昴＆繧薙・蜒輔ｒ險ｱ縺輔↑縺Ы01.jpg...
```

---

3. `ValueError: Unfamiliar width
https://shonenjumpplus.com/magazine/3270296674401895776.json`

```shellsession
$ jget -u "xxxxxxxxxxx@xxxxxxxx" -p "xxxxxxxxxxxxxxxx" "https://shonenjumpplus.com/magazine/3270296674401895776.json"
get: https://shonenjumpplus.com/magazine/3270296674401895776.json
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\jget.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\getjump\main.py", line 175, in main
    get_one(args)
  File "c:\programdata\anaconda3\lib\site-packages\getjump\main.py", line 154, in get_one
    _, prev_title, ok = g.get(
  File "c:\programdata\anaconda3\lib\site-packages\getjump\getjump.py", line 98, in get
    self.__save_images(pages, save_dir, only_first)
  File "c:\programdata\anaconda3\lib\site-packages\getjump\getjump.py", line 167, in __save_images
    img = self.__get_image(page)
  File "c:\programdata\anaconda3\lib\site-packages\getjump\getjump.py", line 187, in __get_image
    dice_width = int((width - self.__get_width_gap(width)) / offset)
  File "c:\programdata\anaconda3\lib\site-packages\getjump\getjump.py", line 227, in __get_width_gap
    raise ValueError(
ValueError: Unfamiliar width (please let me know with issue <https://git.io/J2jV3>): 959
```

度々すみません ご対応いただけると嬉しいです

**Comment by eggplants** [comment]
1と2に関してはWindowsに問題があるようです。Linux環境では正常にダウンロードと閲覧ができました。

3は定期購読が必要なので今の所検証していません。

**Comment by eggplants** [comment]
3ですが、

```bash
git clone https://github.com/eggplants/getjump && cd getjump
pip instal -e .
```

した後、`getjump/gap.py`の`WIDTH_GAP`に`959: 0,`などを追記して

```bash
getjump -o -f -u "***" -p "***" "https://shonenjumpplus.com/magazine/3270296674401895776.json"
```

で1ページだけダウンロードし、画像がずれているようなら`959: 2,`などと数字を増やしていい感じの値を探索すると解決できます。

**Comment by eggplants** [comment]
1と2についてはこれっぽい
https://qiita.com/SKYS/items/cbde3775e2143cad7455
