### ISSUE TITLE
Unfamiliar width: 959

### ISSUE THREAD

**Issue by eggplants** [eggplants/getjump#22]
ref: #21 

```shellsession
$ jget -u "xxxxxxxxxxx@xxxxxxxx" -p "xxxxxxxxxxxxxxxx" "https://shonenjumpplus.com/magazine/3270296674401895776.json"
get: https://shonenjumpplus.com/magazine/3270296674401895776.json
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\jget.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\getjump\main.py", line 175, in main
    get_one(args)
  File "c:\programdata\anaconda3\lib\site-packages\getjump\main.py", line 154, in get_one
    _, prev_title, ok = g.get(
  File "c:\programdata\anaconda3\lib\site-packages\getjump\getjump.py", line 98, in get
    self.__save_images(pages, save_dir, only_first)
  File "c:\programdata\anaconda3\lib\site-packages\getjump\getjump.py", line 167, in __save_images
    img = self.__get_image(page)
  File "c:\programdata\anaconda3\lib\site-packages\getjump\getjump.py", line 187, in __get_image
    dice_width = int((width - self.__get_width_gap(width)) / offset)
  File "c:\programdata\anaconda3\lib\site-packages\getjump\getjump.py", line 227, in __get_width_gap
    raise ValueError(
ValueError: Unfamiliar width (please let me know with issue <https://git.io/J2jV3>): 959
```

**Comment by minahoku** [comment]
調整したところこちらでした
```
959: 28,
```
