### ISSUE TITLE
Metadata保存をしようとするとエラーを吐く

### ISSUE THREAD

**Issue by minahoku** [eggplants/getjump#266]
2.6.0のアップデート後、metadataを保存するオプションをつけるとエラーを吐きダウンロードができなくなった。metadata保存のオプションをオフにすると問題なくダウンロードが開始する

```
Traceback (most recent call last):
  File "/usr/local/bin/getjump", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/getjump/main.py", line 185, in main
    get_one(args)
  File "/usr/local/lib/python3.8/dist-packages/getjump/main.py", line 163, in get_one
    _, prev_title, ok = g.get(
  File "/usr/local/lib/python3.8/dist-packages/getjump/getjump.py", line 146, in get
    json.dumps(res.json(), indent=4),
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by eggplants** [comment]
https://pypi.org/project/getjump/2.6.1/ で治ったと思います
