### ISSUE TITLE
Cannot save file in Windows

### ISSUE THREAD

**Issue by gyeolls** [eggplants/getjump#30]
```shellsession
$ jget -o https://www.sunday-webry.com/episode/3270375685348681386
get: https://www.sunday-webry.com/episode/3270375685348681386
  Downloading... ---------------------------------------- 100% ( 9/9 pages ) remain: 0:00:00 spent: 0:00:00
⠋ Saving...      ----------------------------------------   0% ( 0/9 pages ) remain: -:--:-- spent: 0:00:00
Traceback (most recent call last):
  File "c:\users\mi010\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\mi010\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mi010\AppData\Local\Programs\Python\Python39\Scripts\jget.exe\__main__.py", line 7, in <module>
  File "c:\users\mi010\appdata\local\programs\python\python39\lib\site-packages\getjump\main.py", line 193, in main
    get_one(args)
  File "c:\users\mi010\appdata\local\programs\python\python39\lib\site-packages\getjump\main.py", line 171, in get_one
    _, prev_title, ok = g.get(
  File "c:\users\mi010\appdata\local\programs\python\python39\lib\site-packages\getjump\getjump.py", line 130, in get
    self.__save_images(pages, save_dir, only_first, print_log=print_log)
  File "c:\users\mi010\appdata\local\programs\python\python39\lib\site-packages\getjump\getjump.py", line 235, in __save_images
    img.save(save_img_path)
  File "c:\users\mi010\appdata\local\programs\python\python39\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '.\\古見さんは、コミュ症です。\\365. コミュ363 ちゅー (無理のな い範囲) です。 \\0.jpg'
```

https://www.sunday-webry.com/episode/3270375685348681386

**Comment by eggplants** [comment]
In MacOS and Ubuntu it saved without error. It looks like getjump has to properly escape the work and story names for the Windows path.

**Comment by eggplants** [comment]
@gyeolls
> '.\\古見さんは、コミュ症です。\\365. コミュ363 ちゅー (無理のな い範囲) です。 \\0.jpg'

Are these spaces in the story names actual output?

**Comment by eggplants** [comment]
```shellsession
$ getjump -f "https://www.sunday-webry.com/episode/3270375685348681386"
 get: https://www.sunday-webry.com/episode/3270375685348681386
 Traceback (most recent call last):
 Downloading... ------------ 100% ( 1/1 pages ) remain: 0:00:00 spent: 0:00:00
 File "d:\a\getjump\getjump\getjump\getjump.py", line 235, in __save_images
 img.save(save_img_path)
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\PIL\Image.py", line 2317, in save
 fp = builtins.open(filename, "w+b")
 FileNotFoundError: [Errno 2] No such file or directory: '.\\\u53e4\u898b\u3055\u3093\u306f\u3001\u30b3\u30df\u30e5\u75c7\u3067\u3059\u3002\\365. \u30b3\u30df\u30e5363 \u3061\u3085\u30fc (\u7121\u7406\u306e\u306a\u3044\u7bc4\u56f2) \u3067\u3059\u3002 \\0.jpg'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\Scripts\getjump-script.py", line 33, in <module>
 sys.exit(load_entry_point('getjump', 'console_scripts', 'getjump')())
 File "d:\a\getjump\getjump\getjump\main.py", line 193, in main
 get_one(args)
 File "d:\a\getjump\getjump\getjump\main.py", line 171, in get_one
 _, prev_title, ok = g.get(
 File "d:\a\getjump\getjump\getjump\getjump.py", line 130, in get
 self.__save_images(pages, save_dir, only_first, print_log=print_log)
 File "d:\a\getjump\getjump\getjump\getjump.py", line 217, in __save_images
 with progress:
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\rich\progress.py", line 1174, in __exit__
 self.stop()
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\rich\progress.py", line 1160, in stop
 self.live.stop()
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\rich\live.py", line 147, in stop
 with self.console:
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\rich\console.py", line 848, in __exit__
 self._exit_buffer()
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\rich\console.py", line 806, in _exit_buffer
 self._check_buffer()
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\rich\console.py", line 1999, in _check_buffer
 legacy_windows_render(
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
 term.write_styled(text, style)
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\rich\_win32_console.py", line 442, in write_styled
 self.write_text(text)
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\rich\_win32_console.py", line 403, in write_text
 self.write(text)
 File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\encodings\cp1252.py", line 19, in encode
 return codecs.charmap_encode(input,self.errors,encoding_table)[0]
 UnicodeEncodeError: 'charmap' codec can't encode character '\u2834' in position 0: character maps to <undefined>
```

**Comment by eggplants** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '.\古見さんは、コミュ症です。\365. コミュ363 ちゅー (無理のない範囲) です。 \0.jpg'
```

**Comment by eggplants** [comment]
https://github.com/eggplants/getjump/runs/7455374769?check_suite_focus=true

```shellsession
$ tree .
Folder PATH listing for volume Temporary Storage
Volume serial number is 00000227 0835:AE7F
D:\A\GETJUMP\GETJUMP
+---.github
�   +---workflows
+---getjump
�   +---__pycache__
+---getjump.egg-info
+---tests
+---?????????????
    +---365. ???363 ??? (???????) ???
```

**Comment by gyeolls** [comment]
The free release date for the corresponding session is until the 24th Can I work this out?

**Comment by eggplants** [comment]
Maybe title's trailing space caused this issue.

```
365. コミュ363 ちゅー (無理のない範囲) です。 
                                    ^- here
```

It seems the space was stripped only in Windows somehow.

**Comment by eggplants** [comment]
https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/file-folder-name-whitespace-characters
>File and Folder names that begin or end with the ASCII Space (0x20) will be saved without these characters. File and Folder names that end with the ASCII Period (0x2E) character will also be saved without this character. All other trailing or leading whitespace characters are retained.
