### ISSUE TITLE
URL が **/volume/** のときダウンロードができない

### ISSUE THREAD

**Issue by tgw314** [eggplants/getjump#45]
```
get: https://comic-days.com/volume/10834108156644567507.json
Traceback (most recent call last):
  File "/home/tagawa/.local/bin/jget", line 8, in <module>
    sys.exit(main())
  File "/home/tagawa/.local/pipx/venvs/getjump/lib/python3.10/site-packages/getjump/main.py", line 193, in main
    get_one(args)
  File "/home/tagawa/.local/pipx/venvs/getjump/lib/python3.10/site-packages/getjump/main.py", line 171, in get_one
    _, prev_title, ok = g.get(
  File "/home/tagawa/.local/pipx/venvs/getjump/lib/python3.10/site-packages/getjump/getjump.py", line 110, in get
    save_dir = os.path.join(save_path, series_title, title)
UnboundLocalError: local variable 'series_title' referenced before assignment
```

https://github.com/eggplants/getjump/blob/4ea343ddae3a2a3fb9d8d71b8cb76365ce29717c/getjump/getjump.py#L102-L107

`volume` の場合が考慮されていないので、`title` `series_title` が定義されないようです

**Comment by eggplants** [comment]
https://pypi.org/project/getjump/2.2.0/
を試してみてください。
